name: Voting App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: |
        docker build -t $DOCKER_HUB_USERNAME/vote:${{ github.sha }} voting-app/vote
        docker build -t $DOCKER_HUB_USERNAME/result:${{ github.sha }} voting-app/result
        docker build -t $DOCKER_HUB_USERNAME/worker:${{ github.sha }} voting-app/worker

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker images
      run: |
        docker push $DOCKER_HUB_USERNAME/vote:${{ github.sha }}
        docker push $DOCKER_HUB_USERNAME/result:${{ github.sha }}
        docker push $DOCKER_HUB_USERNAME/worker:${{ github.sha }}

  update_manifests:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: camesa/voting-app-k8s
        token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    - name: Update Kubernetes manifests
      run: |
        for service in vote result worker; do
          sed -i "s|image: $DOCKER_HUB_USERNAME/$service:.*|image: $DOCKER_HUB_USERNAME/$service:${{ github.sha }}|g" k8s-manifests/$service.yaml
        done
    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add k8s-manifests/*.yaml
        git commit -m "Actualizar imágenes a ${{ github.sha }}"
        git push
