name: Build y Push de Imagenes Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-y-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        servicio: [result, vote, worker]

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesi贸n en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Generar versi贸n
        id: version
        run: echo "VERSION=v0.1.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Construir y publicar imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: ./voting-app/${{ matrix.servicio }}
          push: true
          tags: |
            camesa/voting-app-${{ matrix.servicio }}:latest
            camesa/voting-app-${{ matrix.servicio }}:${{ steps.version.outputs.VERSION }}

      - name: Crear y pushear tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.VERSION }}
          git push origin ${{ steps.version.outputs.VERSION }}

      - name: Imprimir nueva versi贸n
        run: 'echo "Nueva versi贸n creada: ${{ steps.version.outputs.VERSION }}"'
