name: Voting App CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build y push de Docker images
      run: |
        for service in vote result worker; do
          docker build -t $DOCKER_HUB_USERNAME/$service:${{ github.sha }} voting-app/$service
          docker push $DOCKER_HUB_USERNAME/$service:${{ github.sha }}
        done

    - name: Image Tags
      run: |
        echo "Las siguientes imágenes han sido construidas y subidas:"
        echo "vote: $DOCKER_HUB_USERNAME/vote:${{ github.sha }}"
        echo "result: $DOCKER_HUB_USERNAME/result:${{ github.sha }}"
        echo "worker: $DOCKER_HUB_USERNAME/worker:${{ github.sha }}"
