name: Actualizar Manifiestos de Kubernetes

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versión para actualizar en los manifiestos"
        required: true

jobs:
  actualizar-manifiestos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio de manifiestos
        uses: actions/checkout@v3
        with:
          repository: camesa/voting-app-k8s
          token: ${{ secrets.K8S_ACCESS_TOKEN }}

      - name: Actualizar manifiestos
        run: |
          for file in k8s-manifests/*.yaml; do
            servicio=$(basename "$file" .yaml)
            sed -i 's|camesa/voting-app-'"$servicio"':.*|camesa/voting-app-'"$servicio"':${{ github.event.inputs.version }}|g' "$file"
          done

      - name: Commit y push de los cambios
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Actualizar versiones de imágenes a ${{ github.event.inputs.version }}"
          git push
